[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'justinmk/vim-dirvish'
hook_add = '''
  let g:polyglot_disabled = ['latex']
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  nnoremap <Leader><Space> :FZF<CR>
  nnoremap <Leader>f :FZF ~<CR>
  nnoremap <Leader>F :FZF /<CR>
  nnoremap <Leader>g :GFiles<CR>
  nnoremap <Leader>b :Buffers<CR>
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  nnoremap <C-]> :<C-u>LspDefinition<CR>
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_ignore_case = 1
'''

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merged = '0'
hook_add = '''
  let g:lsp_settings = {
  \ 'clangd': {'cmd': ['clangd-7']},
  \ 'pyls-all': {
  \   'workspace_config': {
  \     'pyls': {
  \       'configurationSources': ['flake8']
  \     }
  \   }
  \ },
  \}
'''

[[plugins]]
repo = 'mattn/vim-lsp-icons'
