[[plugins]]
repo = 'sbdchd/neoformat'
on_ft = ['html', 'javascript', 'css', 'typescript', 'markdown']
hook_add = '''
  augroup fmt
    autocmd!
    autocmd BufWritePre * undojoin | Neoformat
  augroup END
'''

[[plugins]]
repo  = 'mattn/emmet-vim'
on_ft = ['html', 'css']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'tpope/vim-speeddating'
on_ft = ['org']

[[plugins]]
repo = 'jceb/vim-orgmode'
on_ft = ['org']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app & yarn install"'
