[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
  call submode#enter_with('bufmove', 'n', '', 'sL', '<C-w>>')
  call submode#enter_with('bufmove', 'n', '', 'sH', '<C-w><')
  call submode#enter_with('bufmove', 'n', '', 'sK', '<C-w>+')
  call submode#enter_with('bufmove', 'n', '', 'sJ', '<C-w>-')
  call submode#map('bufmove', 'n', '', 'L', '<C-w>>')
  call submode#map('bufmove', 'n', '', 'H', '<C-w><')
  call submode#map('bufmove', 'n', '', 'K', '<C-w>+')
  call submode#map('bufmove', 'n', '', 'J', '<C-w>-')
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'map <C-n> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'justinmk/vim-dirvish'
hook_add = '''
  let g:polyglot_disabled = ['latex']
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  let g:lsp_highlight_references_enabled = 1
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_ignore_case = 1
  set completeopt-=preview
'''

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merged = '0'
hook_add = '''
  let g:lsp_settings = {
  \ 'clangd': {'cmd': ['clangd-7']},
  \ 'typescript-language-server': {
  \   'cmd': [&shell, &shellcmdflag, 'typescript-language-server --stdio']
  \ },
  \ 'pyls-all': {
  \   'workspace_config': {
  \     'pyls': {
  \       'configurationSources': ['flake8']
  \     }
  \   }
  \ },
  \}
'''

[[plugins]]
repo = 'mattn/vim-lsp-icons'
