[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
  call submode#enter_with('bufmove', 'n', '', 'sL', '<C-w>>')
  call submode#enter_with('bufmove', 'n', '', 'sH', '<C-w><')
  call submode#enter_with('bufmove', 'n', '', 'sK', '<C-w>+')
  call submode#enter_with('bufmove', 'n', '', 'sJ', '<C-w>-')
  call submode#map('bufmove', 'n', '', 'L', '<C-w>>')
  call submode#map('bufmove', 'n', '', 'H', '<C-w><')
  call submode#map('bufmove', 'n', '', 'K', '<C-w>+')
  call submode#map('bufmove', 'n', '', 'J', '<C-w>-')
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'nnoremap <C-d> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'justinmk/vim-dirvish'
hook_add = '''
  let g:polyglot_disabled = ['latex']
'''

[[plugins]]
repo = 'powerline/powerline'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'sbdchd/neoformat'
